#!/usr/bin/env bash
#
# Generated by facility — https://github.com/theam/facility
#
# Reflect the invoked agent on the org GitHub Project board by setting the
# triggering issue's "Status" field:
#
#   /architect -> Planning      (only advances from empty/Backlog; never backward)
#   /builder   -> In Progress   (invoking /builder is acceptance of the plan)
#   verified delivery -> In Review
#
# Forward-only: the board is never moved backward (an issue already in
# "In Review"/"Done" is left alone). The script no-ops cleanly when the
# PROJECTS_PAT secret is missing, so the crew keeps working before the token
# is configured.
#
# Requires: gh, jq. Auth via GH_TOKEN (a PAT/App token with org Projects
# read+write; the default GITHUB_TOKEN cannot write org-level Projects v2).
#
# Env: MODE (builder|architect|review), ISSUE_NODE_ID, ORG, PROJECT_NUMBER.
# Optional env to adapt to your board's column names:
#   STATUS_COLUMNS    ordered, comma-separated (default below)
#   ARCHITECT_STATUS  target column for /architect (default "Planning")
#   BUILDER_STATUS    target column for /builder (default "In Progress")
#   REVIEW_STATUS     target column after verified delivery (default "In Review")
set -euo pipefail

: "${MODE:?MODE required}"
: "${ISSUE_NODE_ID:?ISSUE_NODE_ID required}"
: "${ORG:?ORG required}"
: "${PROJECT_NUMBER:?PROJECT_NUMBER required}"
STATUS_COLUMNS="${STATUS_COLUMNS:-Backlog,Planning,Ready,In Progress,In Review,Done}"
ARCHITECT_STATUS="${ARCHITECT_STATUS:-Planning}"
BUILDER_STATUS="${BUILDER_STATUS:-In Progress}"
REVIEW_STATUS="${REVIEW_STATUS:-In Review}"

if [ -z "${GH_TOKEN:-}" ]; then
  echo "::notice::PROJECTS_PAT not configured — skipping Project #${PROJECT_NUMBER} status move."
  exit 0
fi

case "$MODE" in
  architect) TARGET="$ARCHITECT_STATUS" ;;
  builder)   TARGET="$BUILDER_STATUS" ;;
  review)    TARGET="$REVIEW_STATUS" ;;
  *) echo "::notice::mode '$MODE' has no status mapping — skipping."; exit 0 ;;
esac

# gh api graphql with a small retry — the GitHub API occasionally returns a
# transient 401/5xx that succeeds on a second attempt.
gql() {
  local attempt out err
  err=$(mktemp)
  for attempt in 1 2 3; do
    if out=$(gh api graphql "$@" 2>"$err"); then printf '%s' "$out"; rm -f "$err"; return 0; fi
    sleep $((attempt * 2))
  done
  echo "::warning::GraphQL call failed after 3 attempts: $(tail -n1 "$err")" >&2
  rm -f "$err"
  return 1
}

# --- Project + Status single-select field metadata ---
proj_json=$(gql -F number="$PROJECT_NUMBER" -f org="$ORG" -f query='
  query($org:String!, $number:Int!) {
    organization(login:$org) {
      projectV2(number:$number) {
        id
        field(name:"Status") {
          ... on ProjectV2SingleSelectField { id options { id name } }
        }
      }
    }
  }')

PROJECT_ID=$(jq -r '.data.organization.projectV2.id // ""' <<<"$proj_json")
STATUS_FIELD_ID=$(jq -r '.data.organization.projectV2.field.id // ""' <<<"$proj_json")
TARGET_OPTION_ID=$(jq -r --arg n "$TARGET" \
  '.data.organization.projectV2.field.options[]? | select(.name==$n) | .id' <<<"$proj_json")

if [ -z "$PROJECT_ID" ] || [ -z "$STATUS_FIELD_ID" ] || [ -z "$TARGET_OPTION_ID" ]; then
  echo "::warning::Could not resolve Project #${PROJECT_NUMBER} / Status option '$TARGET' — skipping."
  exit 0
fi

# --- Find the item for this issue on the project (add it if missing) ---
item_json=$(gql -f issue="$ISSUE_NODE_ID" -f query='
  query($issue:ID!) {
    node(id:$issue) {
      ... on Issue {
        projectItems(first:50) {
          nodes {
            id
            project { id }
            fieldValueByName(name:"Status") {
              ... on ProjectV2ItemFieldSingleSelectValue { name }
            }
          }
        }
      }
    }
  }')

ITEM_ID=$(jq -r --arg p "$PROJECT_ID" \
  '.data.node.projectItems.nodes[]? | select(.project.id==$p) | .id' <<<"$item_json")
CURRENT=$(jq -r --arg p "$PROJECT_ID" \
  '.data.node.projectItems.nodes[]? | select(.project.id==$p) | .fieldValueByName.name // ""' <<<"$item_json")

if [ -z "$ITEM_ID" ]; then
  ITEM_ID=$(gql -f project="$PROJECT_ID" -f content="$ISSUE_NODE_ID" -f query='
    mutation($project:ID!, $content:ID!) {
      addProjectV2ItemById(input:{projectId:$project, contentId:$content}) { item { id } }
    }' --jq '.data.addProjectV2ItemById.item.id')
  CURRENT=""
  echo "Added issue to Project #${PROJECT_NUMBER} (item ${ITEM_ID})."
fi

# --- Forward-only guard (board column order from STATUS_COLUMNS) ---
rank() {
  local name="$1" i=0 col
  if [ -z "$name" ]; then echo 0; return; fi
  IFS=',' read -ra cols <<< "$STATUS_COLUMNS"
  for col in "${cols[@]}"; do
    if [ "$col" = "$name" ]; then echo "$i"; return; fi
    i=$((i + 1))
  done
  echo 0
}
cur_rank=$(rank "$CURRENT")
tgt_rank=$(rank "$TARGET")

# /architect only kicks off planning; if work has already moved past the first
# column, leave the board as-is (a follow-up question shouldn't drag it back).
if [ "$MODE" = "architect" ] && [ "$cur_rank" -gt 0 ]; then
  echo "::notice::Issue already at '${CURRENT}' — /architect leaves the board unchanged."
  exit 0
fi
# Never move backward or sideways.
if [ -n "$CURRENT" ] && [ "$tgt_rank" -le "$cur_rank" ]; then
  echo "::notice::Issue at '${CURRENT}'; not moving to '${TARGET}' (forward-only)."
  exit 0
fi

# --- Apply ---
gql \
  -f project="$PROJECT_ID" -f item="$ITEM_ID" -f field="$STATUS_FIELD_ID" -f option="$TARGET_OPTION_ID" \
  -f query='
    mutation($project:ID!, $item:ID!, $field:ID!, $option:String!) {
      updateProjectV2ItemFieldValue(input:{
        projectId:$project, itemId:$item, fieldId:$field,
        value:{ singleSelectOptionId:$option }
      }) { projectV2Item { id } }
    }' >/dev/null

echo "Moved issue to '${TARGET}' on Project #${PROJECT_NUMBER} (was '${CURRENT:-unset}')."
