#!/usr/bin/env node
// Generated by facility — https://github.com/theam/facility
//
// Weekly synthetic canary. Flies the REAL pipeline: posts the canonical
// /architect probe on the pinned canary issue, then asserts the crew run
// appears, succeeds, and replies. Any broken link turns this workflow red,
// and the health monitor (which watches facility-canary) raises it in the
// incident issue the next morning.
//
// Authorization is by MESSAGE, not by sender: the crew workflow admits the
// canary bot only for a comment that is byte-identical (SHA-256, CR-stripped)
// to CANARY_PROBE_BODY below, on an agent-canary-labeled issue, resolving to
// /architect. Within the crew trigger that blocks attacker-chosen
// instructions, but the hash is an instruction-content gate, not a replay or
// cost boundary: the token can post the fixed probe repeatedly, and it can
// exercise any other GitHub permissions it carries. The generated workflow
// narrows its minted token to Issues: write. Keep the backing App dedicated to
// canary repositories with Issues: read and write as its only requested
// repository permission, because its private key can mint tokens up to the
// App's installed permissions. The pinned hash in facility-crew.yml is kept in
// sync by the watchtower-locked guard.
//
// The probe must be posted with a GitHub App or PAT token (CANARY_COMMENT_TOKEN):
// comments posted with the workflow's own GITHUB_TOKEN trigger no workflows
// at all (GitHub's recursion guard) — the canary would test nothing.
// Env: GH_TOKEN, GITHUB_REPOSITORY, CANARY_COMMENT_TOKEN (App/PAT).
import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { verifyReceipt } from "../receipts/collect.mjs";

export const CANARY_PROBE_BODY = [
  "/architect",
  "",
  "Facility canary probe. This is a scheduled synthetic check of the agent",
  "pipeline, authorized by message hash. Reply with a one-paragraph health",
  "summary of this repository's facility setup (crew workflows present,",
  "STANDARD.md readable, guards runnable) and stop. Do not plan features, do",
  "not read beyond what the summary needs, and do not modify anything.",
].join("\n");

const CREW_WORKFLOW = "facility-crew";
const POLL_SECONDS = 30;
const TIMEOUT_MINUTES = 45;

async function main() {
  const repo = process.env.GITHUB_REPOSITORY;
  if (!repo) throw new Error("GITHUB_REPOSITORY is required");
  const token = process.env.CANARY_COMMENT_TOKEN;
  if (!token) {
    console.log(
      "::notice::CANARY_COMMENT_TOKEN not configured — canary skipped. Mint it from a GitHub App so the probe comment triggers workflows.",
    );
    return;
  }

  const gh = (args) => execFileSync("gh", args, { encoding: "utf8", maxBuffer: 16 * 1024 * 1024 });
  const api = async (path, init = {}) => {
    const response = await fetch(`https://api.github.com/repos/${repo}/${path}`, {
      ...init,
      headers: {
        authorization: `Bearer ${token}`,
        accept: "application/vnd.github+json",
        ...(init.headers ?? {}),
      },
    });
    if (!response.ok) throw new Error(`${path} → ${response.status}: ${await response.text()}`);
    return response.json();
  };

  // 1. Find (or create) the pinned canary fixture issue.
  try {
    gh([
      "label",
      "create",
      "agent-canary",
      "--force",
      "--color",
      "FFD923",
      "--description",
      "facility canary fixture",
    ]);
  } catch {}
  const issues = JSON.parse(
    gh([
      "issue",
      "list",
      "--label",
      "agent-canary",
      "--state",
      "open",
      "--json",
      "number",
      "--limit",
      "1",
    ]),
  );
  let issueNumber = issues[0]?.number;
  if (!issueNumber) {
    const createdUrl = gh([
      "issue",
      "create",
      "--title",
      "Facility canary",
      "--label",
      "agent-canary",
      "--body",
      "Pinned fixture issue for the weekly synthetic canary. The probe comments below are posted by the canary workflow; do not comment agent commands here yourself.",
    ]).trim();
    issueNumber = Number(createdUrl.split("/").pop());
    if (!issueNumber) throw new Error(`could not parse issue number from: ${createdUrl}`);
  }

  // 2. Post the canonical probe with the App token (so it triggers workflows).
  const startedAt = new Date().toISOString();
  await api(`issues/${issueNumber}/comments`, {
    method: "POST",
    body: JSON.stringify({ body: CANARY_PROBE_BODY }),
  });
  console.log(`probe posted on #${issueNumber} at ${startedAt}`);

  // 3. Assert the crew run appears and succeeds.
  const deadline = Date.now() + TIMEOUT_MINUTES * 60_000;
  let run = null;
  while (Date.now() < deadline) {
    const { workflow_runs: runs } = JSON.parse(
      gh([
        "api",
        `repos/${repo}/actions/runs?event=issue_comment&created=>${startedAt}&per_page=20`,
      ]),
    );
    run = runs.find((r) => r.name === CREW_WORKFLOW) ?? null;
    if (run && run.status === "completed") break;
    await new Promise((resolve) => setTimeout(resolve, POLL_SECONDS * 1000));
  }
  if (!run)
    throw new Error(
      `no ${CREW_WORKFLOW} run appeared within ${TIMEOUT_MINUTES} minutes — the trigger chain is broken`,
    );
  if (run.conclusion !== "success")
    throw new Error(`crew run concluded '${run.conclusion}': ${run.html_url}`);

  // 4. Download and verify the receipt produced by THIS exact crew run. A
  // green workflow conclusion without its signed evidence is not a green
  // agent flight.
  const artifactName = `facility-run-receipt-${run.id}-crew`;
  const receiptDir = mkdtempSync(join(tmpdir(), "facility-canary-receipt-"));
  let receipt;
  let receiptPath;
  try {
    gh([
      "run",
      "download",
      String(run.id),
      "--repo",
      repo,
      "--name",
      artifactName,
      "--dir",
      receiptDir,
    ]);
    receiptPath = findFile(receiptDir, "facility-run.json");
    if (!receiptPath) throw new Error(`${artifactName} did not contain facility-run.json`);
    receipt = JSON.parse(readFileSync(receiptPath, "utf8"));
    if (!verifyReceipt(receipt))
      throw new Error(`${artifactName} failed its SHA-256 integrity check`);
    if (
      receipt.provider !== "claude_code" ||
      receipt.mode !== "architect" ||
      receipt.result !== "succeeded" ||
      receipt.github?.issue !== issueNumber ||
      !String(receipt.run_id ?? "").startsWith(`${run.id}:`)
    ) {
      throw new Error(`${artifactName} does not describe this architect canary run`);
    }
    gh(["attestation", "verify", receiptPath, "--repo", repo]);
  } finally {
    rmSync(receiptDir, { recursive: true, force: true });
  }

  // 5. Assert a reply landed on the issue after the probe.
  const comments = JSON.parse(
    gh(["api", `repos/${repo}/issues/${issueNumber}/comments?per_page=100`]),
  );
  const reply = comments.find((c) => c.created_at > startedAt && c.body !== CANARY_PROBE_BODY);
  if (!reply)
    throw new Error(
      `crew run succeeded but no reply landed on #${issueNumber} — the reply chain is broken`,
    );

  console.log(
    `canary green: run ${run.html_url} · receipt ${receipt.integrity.payload_sha256} (attested) · reply ${reply.html_url}`,
  );
}

function findFile(dir, name) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      const nested = findFile(path, name);
      if (nested) return nested;
    } else if (entry.name === name) {
      return path;
    }
  }
  return null;
}

// Import-safe: the watchtower-locked guard imports CANARY_PROBE_BODY without running the probe.
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop())) {
  main().catch((error) => {
    console.error(`::error::${error.message}`);
    process.exit(1);
  });
}
